### ISSUE TITLE
a question on RuntimeError: CUDA error: out of memory

### ISSUE THREAD

**Issue by arf111** [znxlwm/pytorch-CartoonGAN#1]
hello there, I am currently facing an issue of cuda out of memory for running this code. I have Nvidia 1060 6GB. Is there any way to solve this issue?

**Comment by znxlwm** [comment]
Hi,
The default batch size for this repo is 8. Reduce the batch size to fit your GPU.

`python CartoonGAN.py --name your_project_name --src_data src_data_path --tgt_data tgt_data_path --vgg_model pre_trained_VGG19_model_path --batch_size batch_size`

**Comment by arf111** [comment]
> Hi,
> The default batch size for this repo is 8. Reduce the batch size to fit your GPU.
> 
> `python CartoonGAN.py --name your_project_name --src_data src_data_path --tgt_data tgt_data_path --vgg_model pre_trained_VGG19_model_path --batch_size batch_size`

Thank you so much.

**Comment by arf111** [comment]
> Hi,
> The default batch size for this repo is 8. Reduce the batch size to fit your GPU.
> 
> `python CartoonGAN.py --name your_project_name --src_data src_data_path --tgt_data tgt_data_path --vgg_model pre_trained_VGG19_model_path --batch_size batch_size`

Thank you so much
