### ISSUE TITLE
VGG input

### ISSUE THREAD

**Issue by ShuvenduRoy** [znxlwm/pytorch-CartoonGAN#3]
https://github.com/znxlwm/pytorch-CartoonGAN/blob/fa4f9a335151d91b2afced9c1eb59679117300d7/CartoonGAN.py#L111

Why +1 and divide by 2 is used here??

**Comment by znxlwm** [comment]
range of x is -1 ~ 1.
So, I used +1 and divide by 2 to normalize from -1 ~ 1 to 0 ~ 1.
